cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "1"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "30"
use-conda: "False"
use-singularity: "False"
jobs: "500"
printshellcmds: "True"
